[package]
name = "artspace_shared"
description = "Shared type definitions for Artspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
structmap = { workspace = true }
structmap-derive = { workspace = true }
redis = { workspace = true }
redis-macros = { workspace = true }

ts-rs = { version = "8.1.0", features = ["serde-compat"] }
