// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WeirdAssName = { id: string, content: string, imageKey: string, createdAt: string, userId: number, };