[package]
name = "artspace_core"
description = "Core rust package for Artspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

artspace_shared = { path = "../artspace-shared" }

#fn_s3_proc
image = { workspace = true }
rayon = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
redis = { workspace = true, features = ["tokio-comp"] }

strum = { workspace = true }

structmap = { workspace = true }
structmap-derive = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ['full', 'test-util'] }
