// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubscribeMessage } from "./SubscribeMessage";

export type ClientMessage = { "subscribe": SubscribeMessage };